### PR TITLE
implemented the language selection scene

### PR DESCRIPTION
**Pull request by developer0623**

### CODE REVIEW

**Comment by umurb** [comment]
@polinasoshkina any comments on the implementation?

### Language Selection

How can we make it more clear to user that there are more than 5 languages we are offering and that they can scroll down the options? 

screen shot 2018-09-04 at 2 11 03 pm
---
### ToS & PP
screen shot 2018-09-04 at 2 10 55 pm

**Comment by polinasoshkina** [comment]
There are a number of approaches:
1. Fade out half of the last item so it's clear that you can scroll down
2. Show a scroll bar
3. Take both steps out to a modal in the center of the screen that can
display all the languages.

**Comment by umurb** [comment]
When scrolled all the way to the bottom, the last item should no longer be faded-out. Instead, the item on the top should be faded-out.  
screen shot 2018-09-05 at 9 55 37 am

**Comment by umurb** [comment]
LanguageSelectionModal should show the translated versions as soon as a nre language is selected. It currently is not;
languagemodal-translationbug

**Comment by umurb** [comment]
@developer0623 one last request;

Can you adjust the scroll-down default so that the selected language is visible everytime I visit the language selection modal?

empty-language-scroll

**Pull request merged**
