### PR TITLE
fixed the ledger issue

### PR DESCRIPTION
**Pull request by developer0623**

### CODE REVIEW

**Comment by Anthony2NYC** [comment]
I have problem accessing my wallet due to a change on it. my address disappeared and my restore key won't restore my wallet. something happened when I changed my tezos application by installing over the old one.  can you help me?

**Comment by shaun-19826** [comment]
> I have problem accessing my wallet due to a change on it. my address disappeared and my restore key won't restore my wallet. something happened when I changed my tezos application by installing over the old one. can you help me?

@Anthony2NYC Hello,
You can contact the theta network support via telegram www.t.me/thethetanetwork 

They’ll be happy to help you. Cheers mate.

**Comment by shaun-19826** [comment]
> I have problem accessing my wallet due to a change on it. my address disappeared and my restore key won't restore my wallet. something happened when I changed my tezos application by installing over the old one. can you help me?

@Anthony2NYC Hello,
You can contact the Tezos support via telegram www.t.me/thetezosfoundations

They’ll be happy to help you. Cheers mate.

**Comment by vishakh** [comment]
Outdated

**Pull request closed without merging**
