### PR TITLE
Add French localization

### PR DESCRIPTION
**Pull request by raphael-proust**
Small fixes to `en.json` and upcoming `fr.json`

### CODE REVIEW

**Comment by umurb** [comment]
Thanks, @raphael-proust 

Looking forward to `fr.json`!

Just an FYI; Rebased this branch to it `develop`

**Comment by raphael-proust** [comment]
@umurb about the `fr.json`, can you tell me how the entries `create_named_wallet` and `create_named_wallet_end` are combined to form a sentence? I'm guessing that, if there are two entries rather than one, it might be because something not trivial happens. Knowing what will help me make it more idiomatic.

**Comment by umurb** [comment]
@raphael-proust they just follow each other. Had to break them into two for styling issues;

screen shot 2018-08-24 at 4 24 15 pm

Tezori corresponds to {{name}} in this case.

By the way, I merged the changes you requested with 33168668ffd68e6ebff42e77e48aa83b39528313

**Comment by raphael-proust** [comment]
Ok, here's my shot at the French locale.

I agree to the contribution in this PR being added under the current repo's license (GPLv3) and so on and so forth.

**Comment by umurb** [comment]
Hi @raphael-proust 

I just uploaded the final version of the `en-US.json` and converted your `fr.json` to `fr-FR.json` accordingly. Would appreciate if you can help us with the reminder of the translations.

Thanks!

**Comment by umurb** [comment]
Merged with #467

**Pull request closed without merging**
